name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2"

      - name: Install deps
        run: bun install --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint
        run: bun run lint:ci

      - name: Lint markdown
        run: bun run lint:md

      - name: Type check
        run: bun run typecheck

      - name: Format check
        run: bun run format:check

      - name: Test
        run: bun test
